export const usersConst = [
  {
    id: 1,
    name: "Francinaldo Assis",
    email: "francinaldo@teste.com",
    user: "francinaldo",
    password: "1111111",
    confirmPassword: "1111111",
    status: "ativo",
    group: {
      id: 2,
      name: "Administrativo",
    },
  },
  {
    id: 2,
    name: "Luiz Mareze",
    email: "luiz@teste.com",
    user: "luiz",
    password: "1111111",
    confirmPassword: "1111111",
    status: "inativo",
    group: {
      id: 5,
      name: "Master",
    },
  },
  {
    id: 3,
    name: "Miguel Scarpini",
    email: "miguel@teste.com",
    user: "miguel",
    password: "1111111",
    confirmPassword: "1111111",
    status: "ativo",
    group: {
      id: 5,
      name: "Master",
    },
  },
  {
    id: 4,
    name: "Victor Blanco",
    email: "victor@teste.com",
    user: "victor",
    password: "1111111",
    confirmPassword: "1111111",
    status: "inativo",
    group: {
      id: 5,
      name: "Master",
    },
  },
  {
    id: 5,
    name: "Willy Santos",
    email: "willy@teste.com",
    user: "willy",
    password: "1111111",
    confirmPassword: "1111111",
    status: "inativo",
    group: {
      id: 5,
      name: "Master",
    },
  },
];
